version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Compiling new Swagger documentation...
      - npm run prestart
  build:
    commands:
      - echo Building the app...

artifacts:
  files:
    - '**/*'
  discard-paths: yes